### ISSUE TITLE
Custom CSS does not apply

### ISSUE THREAD

**Issue by jeffminsungkim** [zyra/ionic-image-loader#121]
IonicImageLoader module works completely fine with `<ion-avatar>`. However, when I use this module with a custom CSS class, it seems not working. Perhaps I missed something.

Here's the code.

```html
<ion-content fixed scrollDownOnLoad="true" (tap)="contentMouseDown($event)">
    <div class="message-wrap">
        <div *ngFor="let msg of history"
             class="message"
             [class.left]="msg.uid === toUser.uid"
             [class.right]="msg.uid === fromUser.uid">
            <img-loader class="user-img" [src]="msg.photoURL"></img-loader>
        </div>
    </div>
</ion-content>
```
```css
.message-wrap {
        padding: 0 10px;

        .message {
            position: relative;
            padding: 7px 0;

            .user-img {
                position: absolute;
                border-radius: 45px;
                width: 45px;
                height: 45px;
                box-shadow: 0 0 2px rgba(0, 0, 0, 0.36);
            }
     }
}
```
app.component.ts
```typescript
platform.ready().then((readySource) => {
   imageLoaderConfig.enableSpinner(false);
   imageLoaderConfig.useImageTag(true);
   imageLoaderConfig.setMaximumCacheSize(20 * 1024 * 1024);
});
```

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

**Expected behavior**
Images have to be surrounded by a circle border.

**Actual behavior**
![kakaotalk_2017-12-31-18-30-10_photo_12](https://user-images.githubusercontent.com/6092023/34460732-a3641024-ee5a-11e7-95d7-ed9f796c8a0a.jpeg)
